### ISSUE TITLE
C# Python Track Courses to be completed

### ISSUE THREAD

**Issue by donulty1991** [donulty1991/Treehouse#2]
## TODO
* Courses left to finish *
* [ ] Introduction to visual studio
* [ ] Using GITHUB with Visual Studio
* [ ] C# Basics
* [ ] C# Objects
* [ ] Intermediate C#
* [ ] C# Collections
* [ ] Unit Testing in C#
🌮
